### ISSUE TITLE
需要自动登录账号功能

### ISSUE THREAD

**Issue by dev-techmoe** [mamoe/mirai-console#10]
能否考虑以增加配置文件或命令行参数的方式来实现让mirai-console启动时自动登录账号的功能？

**Comment by ryoii** [comment]
已通过插件实现

**Comment by dev-techmoe** [comment]
请问哪个插件实现了这样的功能，能否提供一下地址？

**Comment by ryoii** [comment]
> 请问哪个插件实现了这样的功能，能否提供一下地址？

目前没有上传，可以加入QQ群获取。预计本周内上传到仓库。
