### ISSUE TITLE
[新功能建议]设置登录QQ账号密码的参数

### ISSUE THREAD

**Issue by lincannm** [mamoe/mirai-console#100]
如题，这样就不用每次都要自己手动输账号密码登录了
像这样，启动的时候我可以：
`java -jar mirai-console.jar -login 1234567890 -pass ab12345678`

**Comment by lincannm** [comment]
抱歉，应该得这样😂。。
`java -jar mirai-console.jar --login 1234567890 --pass ab12345678`

**Comment by Him188** [comment]
自动登录会做，但还没有考虑好以何种方式实现。

**Comment by masnn** [comment]
```sh
echo "login 123456 123456" | java -jar mirai-console.jar
```

跑（

**Comment by YunYouJun** [comment]
也许可以考虑使用 `.env` 文件的形式。

```
BOT_QQ=114514
BOT_PASSWORD=xxxxxx
```

**Comment by MrXiaoM** [comment]
自动登录可以写插件做到，我的做法是在 onEnable() 中添加
```
long qqUid = 0L; // 填写QQ号
String qqPassword = "there is password"; // 填写密码
CommandManager.INSTANCE.runCommand(ConsoleCommandSender.INSTANCE, "login " + qqUid + " " + qqPassword); 
// 完事

```

**Comment by nlpguyz** [comment]
在 config.txt 中写 login 123456 123456 不行吗？我是这么用的，只是会遇到bug，MiraiNative的插件被禁用了。

**Comment by Him188** [comment]
现在计划是增加一个配置文件，以明文密码或MD5方式设置自动登录
