### ISSUE TITLE
配置完成ij后在gradle面板内无mirai选项

### ISSUE THREAD

**Issue by linyuansup** [mamoe/mirai-console#116]
Intellij IDEA版本2020.1，Gradle版本6.2，jdk8，语言Kotlin
按照开发说明内的步骤配置后gradle没有mirai构建的选项

**Comment by Him188** [comment]
插件过期, 现在还未安排更新插件 (后端有更重要的任务)

[mirai-console-intellij](https://github.com/project-mirai/mirai-console-intellij)

**Comment by kettly1260** [comment]
> 插件过期, 现在还未安排更新插件 (后端有更重要的任务)
> 
> [mirai-console-intellij](https://github.com/project-mirai/mirai-console-intellij)

请问现在怎么使用呢？在市场安装最新的mirai-console之后，从idea里面新建项目没有mirai
