### ISSUE TITLE
扩展 MiraiConsole.CommandProcessor.runConsoleCommand 支持完成检测

### ISSUE THREAD

**Issue by LinHeLurking** [mamoe/mirai-console#12]
## 动机
当需要在插件中执行命令时, 由于无法检测命令是否完成, 造成了比较棘手的同步问题. 例如这一段插件中的登录代码(之所以需要用`runConsoleCommand`登录而不是调用`Bot.login()`是因为`Bot.login()`的会和console争抢标准输入输出, 导致无法正常输入验证码)
```kotlin
// 启动一个异步块, 用于登录bot并且注册聊天指令
launch {
    // 以控制台命令方式登录bot
    MiraiConsole.CommandProcessor.runConsoleCommand(
        "/login $qqNumber $password"
    )
    // ? ? ?
    delay(10000)
    // 获取到登陆的bot
    val bot: Bot = try {
        Bot.getInstance(qqNumber)
    } catch (e: Exception) {
        logger.error("Bot($qqNumber) login failed")
        logger.error(e.toString())
        logger.error(e.message)
        return@launch
    }

    /* something else */
}
```
只有插入了一个较长的delay之后再获取Bot才能成功获取, 否则下面的语句在命令完成之前就被执行了. 即使使用`runConsoleCommandBlocking`, 实际上也只是阻塞地把命令送入了`commandChannel: Channel<FullCommand>`, 不过channel的内容仍然是由`processNextCommandLine()`异步执行的, 因此该命令究竟何时完成并不确定. 尽管添加合适的delay可以解决这个问题, 但无论设置多长的时间, 使用`delay()`仍然是一个很不稳定的方法.
## 一个可能的解决方案
由于采用了了异步的channel, 导致`CommandManager.runCommand`的Boolean返回值无法通过runCommand返回. 可以考虑`FullCommand`添加回调方法域, 给`runCommand`等函数添加一个重载, 使得`processNextCommandLine()`中可以在执行完成该命令后执行此回调方法.

**Comment by liujiahua123123** [comment]
将在之后的版本中增加

目前的解决方案: 
可以通过插件(PluginBase)中onCommand()方法监听/login指令, 此时监听到的是已经执行好了的

**Comment by liujiahua123123** [comment]
应该提供一个API 发送指令并阻塞到指令运行结束并返回执行结果

**Comment by Him188** [comment]
或许将 `runCommand` 改为 `suspend`，引入一个 `runCommandAsync`?

**Comment by liujiahua123123** [comment]
现在的依旧保留
增加```runCommandAsync```返回一个deferred
增加```dispatchCommand```阻塞返回执行结果
和    ```dispatchCommandBlocking ```用于java友好
如何

**Comment by liujiahua123123** [comment]
solved
