### ISSUE TITLE
权限系统的设计

### ISSUE THREAD

**Issue by Karlatemp** [mamoe/mirai-console#140]
用处: 扩展 BotManager 权限判断

**Comment by Him188** [comment]
可能不太好实现，或者有没有这样的必要？

**Comment by Him188** [comment]
Manager 权限判断似乎应该是权限系统的问题，如修改一个指令的权限。
确实应该提供一种修改指令权限的方式

**Comment by Karlatemp** [comment]
> 可能不太好实现，或者有没有这样的必要？

我在接入另外一套权限系统(LuckPerms-Mirai)，我希望另外的权限系统判断拥有 XXX 权限时便是mirai-console的manager, 由于现在mirai-console并不是用类似permissionNode:String 来判断权限所以目前我只希望能够接入manager系统

**Comment by Him188** [comment]
那么这可能涉及到权限的设计。当前设计下，指令权限完全由插件实现并提供，可能要考虑变更。

**Comment by Him188** [comment]
但我也不太希望增加字符串-based的 nodes

**Comment by Karlatemp** [comment]
关于 String based的nodes有以下建议

提供
```kotlin
@ConsoleExperimentalAPI
public fun interface IStringBasedPermissionService {
  public fun toMiraiPermission(node: String):CommandPermission
}
internal object DefaultStringBasedPermissionService:IStringBasedPermissionService  {
  override fun toMiraiPermission(node: String):CommandPermission = CommandPermission.None
}
public object StringBasedPermissionService {
  @ConsoleExperimentalAPI
  public var service:IStringBasedPermissionService = DefaultStringBasedPermissionService
  @OptIn(ConsoleExperimentalAPI::class)
  public fun permission(node:String) = service.toMiraiPermission(node)
}
```
或者不提供, 因为我的本意是能够扩展BotManager的判断

**Comment by Him188** [comment]
经考虑, 决定提供 `PermissionService` (或以其他名称), Console 实现基础的仅支持代码实现的权限管理, 并提供 ExtensionPoint 供插件实现

**Comment by Him188** [comment]
对于 `Command` 作者, 他们不再需要考虑权限. 权限将成为仅 `CommandManager` 的职责之一.

**Comment by Karlatemp** [comment]
对于 `Command` 作者, 需要更加细分权限时是否也是通过 `CommandManager` 进行判断

**Comment by Karlatemp** [comment]
> 经考虑, 决定提供 `PermissionService` (或以其他名称), Console 实现基础的仅支持代码实现的权限管理, 并提供 ExtensionPoint 供插件实现

如果考虑使用 `XXXService` 的话，这里的建议是开个新的issue提供专门的 `ServiceManager` , 并且 `PermissionService` 改成 `IPermissionService` 接口, 并在 mirai-console 启动时注册一个最低优先级的默认 `PermissionService`, 每次检查权限都重新获取 `IPermissionService` 实例

对于 ServiceManager:
- 注册新的 `Service` 时直接最加到最后(按优先级排序, 然后是注册时间, 后注册的在后面)
- 搜索时从最高优先级搜索到最低优先级, 提供 Non-Null 的 get 方法的时候附带一个 getOrNull
- 优先级考虑使用数字时，不限制数值大小(即允许负数)

**Comment by Him188** [comment]
我个人希望使用 `interface PermissionService`，然后应其 companion 实现 INSTANCE（就像现在的 `MiraiConsole`）

console 的实现类有更详细的命名，实现细节被 `internal` 隐藏， `StringBasePermissionServiceImpl`

**Comment by Him188** [comment]
当然这会是一个很大的设计问题

**Comment by Karlatemp** [comment]
关于权限系统的设计，这是个挺严谨的问题，可能需要更多方讨论之后才能确定，对于如何优雅的设计也是个很大的问题。因为这可能意味着现在的权限系统将会被完全重写。并且得提供插件选择时候哪种方式进行权限判断，需要更多方的讨论

**Comment by Karlatemp** [comment]
**草案**

提供 `CommandSender.hasPermission(permission: Any): Boolean`,
`typealias PermissionProviderSelector = (sender:CommandSender,permission: Any) -> PermissionProvider?`,
`typealias PermissionProvider = (sender:CommandSender, permission: Any) -> Boolean`

selector负责选择权限该使用何种 provider, 当 selector 返回 null 的时候, 继续检测下一个selector, 如果直到最后都没有正确的 provider, hasPermission返回 false

提供一个 `PermissionProviderService`, 存储 `List<PermissionProviderSelector>`(可以换成线程安全的ConcurrentLinkedQueue), PPS 提供 `registerSelector` 以允许注册一直新的权限类型.

`CommandSender.hasPermission(permission:Any)` 实现细节
1. 遍历 PPS.selectors, 找到符合的selector, 如果没有符合的selector, 直接返回 false
2. 得到provider, 直接返回 provider(sender, permission)
3. 如果有需要, 可以加上 runCatching
