### ISSUE TITLE
在config.txt中加login自动登录后，MiraiNative插件不能自动启用

### ISSUE THREAD

**Issue by nlpguyz** [mamoe/mirai-console#141]
如果不在config.txt自动登录，而是手动从控制台输入login命令，MiraiNative的插件可以自动启用（在config.json中enable即可）。但是，如果是config.txt自动登录的，在完全初始化好之后，MiraiNative载入的插件都是禁用的。需要在login完全完成后，打npm enable 0才能启用。

**Comment by Him188** [comment]
所描述的问题与 mirai-console 均无关. 请确认问题的对象

**Comment by PeratX** [comment]
那说明`BotOnlineEvent`没有被调用

**Comment by Him188** [comment]
不可能, 不广播 `BotOnlineEvent` 事件就不可能完成登录

**Comment by PeratX** [comment]
那需要一个完整复现步骤。
