### ISSUE TITLE
本身/help与插件/help指令冲突

### ISSUE THREAD

**Issue by mengshouer** [mamoe/mirai-console#145]
本身/help的时候会输出权限不足，然后插件的/help也不响应了。

**Comment by Him188** [comment]
插件覆盖默认的“/help”？

**Comment by mengshouer** [comment]
还有。。。我发现给bot添加managers的时候看到了”当只登录了一个 [Bot] 时, 无需上述 `botId` 参数即可“，但实际还是需要botId，添加完manager私聊命令仍然显示权限不足？

**Comment by mengshouer** [comment]
啊，即使加了权限也不输出插件的/help，看来就是本身的自带的commands会优先于插件之前判定然后就没走插件了（？   导致插件内只要和commands内有的指令相同时，就会冲突。

**Comment by Him188** [comment]
插件覆盖默认的“/help”？

**Comment by Him188** [comment]
请提供插件指令的代码

**Comment by mengshouer** [comment]
我是套mirai-native用的cqhttp

**Comment by Him188** [comment]
这属于插件的问题. 插件的指令应该通过 `CommandManager` 注册, 而不是监听消息.

mirai-native 作为一个适配器, 应提供 `PluginLoader` 并转接 `Command` 到 mirai-console. 但由于一些限制, 目前这个功能还没有实现.

请尝试修改 cqhttp 的帮助

**Comment by PragmaTwice** [comment]
我在使用某个 mirai python wrapper （graia）的时候也遇到了这个问题，由于是通过 mirai http api 连接的，所以没有注册命令的方法，只能监听消息，而 /help 等命令被 mirai console 截获，于是无法在 python 端实现 /help，请问有解决方法嘛？感谢。

**Comment by Him188** [comment]
> 我在使用某个 mirai python wrapper （graia）的时候也遇到了这个问题，由于是通过 mirai http api 连接的，所以没有注册命令的方法，只能监听消息，而 /help 等命令被 mirai console 截获，于是无法在 python 端实现 /help，请问有解决方法嘛？感谢。

1.0.0 起 console 不再默认处理指令
