### ISSUE TITLE
踢群人员后，报错！！

### ISSUE THREAD

**Issue by Andy-shi001** [mamoe/mirai-console#147]
![image](https://user-images.githubusercontent.com/68884928/91689333-77750180-eb96-11ea-8fb3-9996fbc59ecd.png)

请更新支持新的console和core，我用的是MiraiOK，目前踢人后就会报错？？

**Comment by Him188** [comment]
更新最新的 core !!

**Comment by Andy-shi001** [comment]
![image](https://user-images.githubusercontent.com/68884928/91695341-8f518300-eba0-11ea-97b0-0cf8e77a2f7f.png)
![image](https://user-images.githubusercontent.com/68884928/91695350-92e50a00-eba0-11ea-8261-59d4744aaac1.png)
![image](https://user-images.githubusercontent.com/68884928/91695361-97112780-eba0-11ea-87bb-79593eaa47de.png)
![image](https://user-images.githubusercontent.com/68884928/91695399-a6907080-eba0-11ea-8a28-7d5dacb6d787.png)

如何更新，更新那个？？
