### ISSUE TITLE
重新设计插件加载过程

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai-console#160]
目前 Console 启动的流程:

```
phase `load configurations`
phase `load BEFORE_EXTENSIONS plugins`
phase `load SingletonExtensionSelector`
phase `load ON_EXTENSIONS plugins`
phase `load PermissionService`
phase `prepare commands`
phase `load AFTER_EXTENSION plugins`
```

如果插件需要提供 `PermissionService`, 则必须在 `ON_EXTENSIONS` 阶段注册权限服务.

但很多插件不只要提供 PS, 还需要注册指令. 然而指令只能在 `AFTER_EXTENSION` 阶段注册.

随着 Console 更新, 现有架构下还会有更多的兼容性问题.

**Comment by Him188** [comment]
### 可能的解决方案 1

在 `onLoad` 阶段注册各类扩展, 如 `CommandProvider`, 之后由 Console 决定初始化顺序.

#### 需要充分考虑的问题
1. 如何处理扩展的 `PluginLoader`?
2. 权限注册如何处理? (指令通常是 `object` 初始化, 可能需要在 `register` 时再注册)

**Comment by Him188** [comment]
> 可能的提案 保持原有加载顺序不变，提供 PhasePreInvokeEvent/PhasePostInvokeEvent，并提供一个id(可以是string)作为识别符 phase `load configurationsphase ` phase&nbsp;`initialize plugins` phase `load BEFORE_EXTENSIONS plugins` phase `load SingletonExtensionSelector` phase `load ON_EXTENSIONS plugins` phase `load PermissionService` phase `prepare commands` phase `load AFTER_EXTENSION plugins` 在initialize plugins这步时，由插件自己在init{}挂钩pre/post event进行事件处理

此方法不具有稳定性. 将来如果去除这个 Phase, 将会是一个巨大的改变. 
另外在 Console 非协程环境广播事件是一个麻烦事情, 可能需要以扩展替代. 那么就与我提的方案 1 类似.

**Comment by Karlatemp** [comment]
或许需要实现一个非协程环境下的事件系统，拥有非协程环境下的事件系统对于console的启动加载过程也有很大帮助，(比如抛弃on enable((对，搬的forge的启动方式)))



---原始邮件---
发件人: "Him188"<notifications@github.com&gt;
发送时间: 2020年9月10日(周四) 晚上10:05
收件人: "mamoe/mirai-console"<mirai-console@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Karlatemp"<karlatemp@vip.qq.com&gt;;
主题: Re: [mamoe/mirai-console] 重新设计插件加载过程 (#160)




  
可能的提案 保持原有加载顺序不变，提供 PhasePreInvokeEvent/PhasePostInvokeEvent，并提供一个id(可以是string)作为识别符 phase load configurationsphase  phase&nbsp;initialize plugins phase load BEFORE_EXTENSIONS plugins phase load SingletonExtensionSelector phase load ON_EXTENSIONS plugins phase load PermissionService phase prepare commands phase load AFTER_EXTENSION plugins 在initialize plugins这步时，由插件自己在init{}挂钩pre/post event进行事件处理
  
此方法不具有稳定性. 将来如果去除这个 Phase, 将会是一个巨大的改变.
 另外在 Console 非协程环境广播事件是一个麻烦事情, 可能需要以扩展替代. 那么就与我提的方案 1 类似.

**Comment by Him188** [comment]
@Karlatemp 请问 Forge 的启动方式具体是怎样的？

**Comment by Karlatemp** [comment]
事件驱动, forge中是mod全部一起先initialize好
然后分别广播 Client/Server InitializeEvent, GameInitializeEvent(没接触过深度forge开发, 可能打错了)等事件, 全程事件驱动, 通知mod现在要做什么
