### ISSUE TITLE
建议优化无权限时的指令响应行为

### ISSUE THREAD

**Issue by KawaiiZapic** [mamoe/mirai-console#161]
自从`console 1.0`以来,指令可以通过向机器人发送消息(包括群消息)时带上`/`前缀来触发指令.  
但是无论是私聊触发还是群触发,主动响应无权限用户执行指令的行为都是不合理的.  

即时聊天不同于游戏服务器,在即时聊天中,`/`不像游戏服务器内具有明确的指向性:
* `/`不一定是指令,而在游戏服务器中被赋予了特殊的意义  
* `/`触发的指令也并非是点对点的,一条消息会被多个bot接收到  

最典型的就是console自带的`/help`指令,这个指令是最常用的,大部分用户见到bot的第一反应大概是想看看这个bot能做什么,但是console却主动注册了这个指令,无法被卸除,无法被覆盖,使开发者在设计bot时的灵活性有所降低.  
同时由于用户默认不会拥有执行任何指令的权限,用户尝试执行时console会主动发送一条"权限不足"给用户,同样无法被卸除,无法被覆盖,也无法被修改.   

脱离开console来说,用户使用`/help`的目标甚至可能不是使用mirai-console的bot,用户可能会感到很莫名其妙.  

无论从何种角度来说,主动响应使用无权限指令的用户都是不合理的,希望未来能在此方面做出改进.

**Comment by myunco** [comment]
确实，建议不要响应群消息中的console指令，会造成一些不必要的困扰。
真要通过QQ消息执行console指令，私聊机器人不是更好的选择吗.
如果需要群内响应，建议可以设置只响应指定群内的消息中的console指令，而不是任何群.

**Comment by Aooober** [comment]
我是从酷Q转过来的，也遇到了这个问题，我用的mirai-native加载酷Q插件，在群里搞了个机器人。
插件的命令都是/开头的，看帮助的命令是/help，但是群员输入/help都是提示权限不足，然后就没有下文了，插件的/help无法被触发，群员看不了帮助。
![QQ截图20200911153259](https://user-images.githubusercontent.com/71117856/92884895-dbc07c80-f444-11ea-894e-0c51051dd3ef.png)
我觉得就算没权限也不应该拦截这条消息，不然插件就没办法处理了。总不能去找插件作者要求改命令吧。
能从作者那要到dll和json就不错了（

**Comment by Him188** [comment]
我早在设计群聊回复时就在代码里添加了 TODO, 现在这样的提示仅是调试作用, 在 1.0-RC 阶段就会增加可以由插件扩展的权限处理方案

**Comment by Him188** [comment]
另外新权限系统即将将在 M4 发布, 可简单管理不同成员的权限, 也支持由插件扩展权限服务

**Comment by CL-Jeremy** [comment]
对于 /help 的问题，我最终选择了[直接干掉 /help](https://github.com/CL-Jeremy/mirai-console-help-forwarder/releases/tag/simply-delete)
对于直接用 systemd 启动 `--no-console` 模式来说，基本够用了
通过修改也可以将内置命令注册成 /help 以外的名字，比如 /?
```kt
object PluginMain : KotlinPlugin(
//[...]
){
    override fun onEnable() {
        //[...]
        HelpCommandOrig.register()
        //[...].grantPermission(parentPermission)
    }
    //[...]
}
object HelpCommandOrig : RawCommand(
    PluginMain, "?",
    description = HelpCommand.description
) {
    override suspend fun CommandSender.onCommand(args: MessageChain) {
        BuiltInCommands.HelpCommand.execute(this, args, false)
    }
}
```

**Comment by ColorfulGhost** [comment]
因此问题困扰而前来报到.......Q_Q

**Comment by Him188** [comment]
将会加入 `CommandCallInterceptor` 允许插件在指令语法解析前, 语法解析后, 调用解析后三个阶段拦截(修改或中断)调用.

**Comment by Him188** [comment]
现决定将聊天环境执行指令的功能从 console 后端删除, 变成由官方支持的插件实现
