### ISSUE TITLE
错误: 找不到或无法加载主类 net.mamoe.mirai.console.pure.MiraiConsolePureLoader

### ISSUE THREAD

**Issue by m839336369** [mamoe/mirai-console#170]
![image](https://user-images.githubusercontent.com/30934916/93010861-7777f700-f5c3-11ea-85c7-025a93af80df.png)
![image](https://user-images.githubusercontent.com/30934916/93010864-7a72e780-f5c3-11ea-81b2-4f5018686ecc.png)
![image](https://user-images.githubusercontent.com/30934916/93010866-7e066e80-f5c3-11ea-8803-1c7d3ef96191.png)
![image](https://user-images.githubusercontent.com/30934916/93010876-91193e80-f5c3-11ea-87b2-ff7e3e81868d.png)

错误: 找不到或无法加载主类 net.mamoe.mirai.console.pure.MiraiConsolePureLoader

**Comment by m839336369** [comment]
java环境没有问题，其他版本也可以用

**Comment by Him188** [comment]
pure 只有 81 KB. 请确认文件完整性. 或者使用 https://github.com/LXY1226/MiraiOK
