### ISSUE TITLE
M4的自动登录求助

### ISSUE THREAD

**Issue by dragon0629** [mamoe/mirai-console#184]
发现console下有个 AutoLogin.yml
plainPasswords: 
  123456654321: example
md5Passwords: 
  123456654321: 1A 79 A4 D6 0D E6 71 8E 8E 5B 32 6E 33 8A E5 33

有大佬可以讲讲怎么修改嘛？这个配置里没有QQ号？

**Comment by Him188** [comment]
123456654321就是 qq号

**Comment by dragon0629** [comment]
谢谢！
