### ISSUE TITLE
补全打包插件相关的文档

### ISSUE THREAD

**Issue by MRDHR** [mamoe/mirai-console#189]
如题，目前我已经在一个项目中编写了多个插件，并使用main函数加载plugin。需要如何操作将我目前编写的插件进行打包？

**Comment by Karlatemp** [comment]
如果您对 gradle 不熟悉的话, 请不要在一个项目中编写多个插件

**Comment by MRDHR** [comment]
那单个工程编写一个插件，是用artifacts去打包就好了？console对manifest有要求么

**Comment by Him188** [comment]
打包相关文档将会在1.0-RC编写
