### ISSUE TITLE
[Feature Request] 添加关闭自动更新依赖的配置项

### ISSUE THREAD

**Issue by dev-techmoe** [mamoe/mirai-console#19]
目前版本的mirai-console个人体验而言已经相对稳定了，希望能有一个能关闭启动时自动更新的办法来锁定版本，为Docker化和部署做准备。

**Comment by liujiahua123123** [comment]
目前还不稳定 在我们认为稳定后会关闭 这是为了你的账号安全考虑

**Comment by Him188** [comment]
目前 core 和 console 都在快速迭代，为保证问题出现时使用的是最新版本，console 需要自动更新。
在第一个正式版发布的时候就会添加自动更新开关
