### ISSUE TITLE
调整版本范围语法

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai-console#194]
1. 区间
数学区间表示
`[1.0.0, 2.0.0]`
`(1.0.0, 2.0.0]`

2. 比较符号
`>= 1.0.0`
`< 2.0.0`

3. 逻辑比较
`A && B`
`A || B`

**Comment by Him188** [comment]
同时可以删除 `SemVersionRangeRequirementBuilder`, 因为上述语法已经有很易用了

**Comment by Karlatemp** [comment]
`SemVersionRangeRequirementBuilder` 可以保留给硬编码使用

**Comment by Him188** [comment]
> `SemVersionRangeRequirementBuilder` 可以保留给硬编码使用

不需要, 字符串表示足够
