### ISSUE TITLE
内置支持选择登录bot时使用哪种登录协议的方法

### ISSUE THREAD

**Issue by Karlatemp** [mamoe/mirai-console#198]
提案

1. `/login [account] [password] [protocol]`
~~2. `/changeprotocol [protocol]`~~
~~3. `./start-mirai-console --protocol [PROTOCOL]`~~

*注: 需要考虑AutoLogin*

**Comment by Him188** [comment]
使用 `BotConfigurationAlterer` 由插件实现

**Comment by Karlatemp** [comment]
那是否还需要给console内置一套供用户选择**默认**协议的方法，还是全部移交 `BotConfigurationAlterer` @Him188

**Comment by Him188** [comment]
> 那是否还需要给console内置一套供用户选择**默认**协议的方法，还是全部移交 `BotConfigurationAlterer` @Him188

我认为不提供“默认”，而是在 `/login` 和 AutoLogin 配置里分账号单独配置。

**Comment by Him188** [comment]
AutoLogin配置将会变得比较复杂, 因此会同时添加一个指令设置自动登录
