### ISSUE TITLE
LoginSolver 中能否提供中断登陆操作的调用

### ISSUE THREAD

**Issue by nyaoouo** [mamoe/mirai-console#207]

**Comment by Him188** [comment]
使用 `BotConfigurationAlterer` 并修改其 `loginSolver`

**Comment by nyaoouo** [comment]
在login solver 中抛出错误后显示Connection lost, retrying login然后继续尝试， 请问中断操作的正确姿势是怎么样

> 使用 `BotConfigurationAlterer` 并修改其 `loginSolver`

**Comment by Karlatemp** [comment]
自行阅读 login solver 注释

**Comment by nyaoouo** [comment]
> 自行阅读 login solver 注释

找到了
