### ISSUE TITLE
实现 `CommandExecuteResult`

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai-console#214]

**Comment by Him188** [comment]
- [ ] `CommandManagerImpl.kt` `executeCommandImpl` 捕获到 `IllegalCommandArgumentException` 时返回 `CommandExecuteResult.IllegalArgument` 而不是 `CommandExecuteResult.ExecutionFailed`

**Comment by Karlatemp** [comment]
- [ ] 为 `CommandExecuteResult.UnresolvedCall` 添加 `val unresolvedKind` 或子类型以区分是主命令未找到(`CommandNotFound`) 还是无法匹配子命令(`ResolveFailed`)
