### ISSUE TITLE
禁止插件使用 ConsoleCommandOwner 构造指令

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai-console#216]
新 ResolveContext

**Comment by Karlatemp** [comment]
`backend` 还未进行检查, 目前仅是ij插件进行了检查

**Comment by Him188** [comment]
我原本不打算在后端检查，在IDE以警告形式提示，可以被Suppress

**Comment by Him188** [comment]
可能会存在某些需要使用 ConsoleCommandOwner 的情况, 因此现在先不在后端限制这个行为

**Comment by Karlatemp** [comment]
已经在后端加上了限制，可能需要放宽限制，允许实现了某个特定marker的command对象使用console command owner
