### ISSUE TITLE
当前最新release如何注册监听事件？

### ISSUE THREAD

**Issue by hisou** [mamoe/mirai-console#218]
之前一直用0.5.2版本，更新到1.0-RC后this.getEventListener().subscribeAlways已经没有了

只会java，新手开发，请多指教。如果有详细文档能指路一下吗

**Comment by Karlatemp** [comment]
请仔细阅读README

https://github.com/mamoe/mirai/blob/master/docs/mirai.md#%E5%BC%80%E5%A7%8B

https://github.com/mamoe/mirai/blob/master/mirai-core/src/jvmMain/kotlin/net/mamoe/mirai/event/JvmMethodListeners.kt
