### ISSUE TITLE
关于如何在安卓手机上运行Mirai-Console-Pure的问题

### ISSUE THREAD

**Issue by I-love-study** [mamoe/mirai-console#22]
本人想在安卓手机上运行Mirai-Console-Pure
但由于Termux不支持jre所以不知道该怎么办(学习python的萌新)
而Mirai-Console-Android也不知道何时能够发布
所以就想问一下现阶段怎么在安卓手机上运行Mirai程序

**Comment by liujiahua123123** [comment]
租一个linux 装到linux上 然后手机ssh上去

**Comment by PeratX** [comment]
https://www.oracle.com/java/technologies/javase-jdk8-downloads.html

自行选择ARM平台的JDK8 并配置环境

Reference: https://github.com/fengberd/PocketServer
