### ISSUE TITLE
如何退出一个指定的bot

### ISSUE THREAD

**Issue by 2659494057** [mamoe/mirai-console#230]
在多bot登录的情况下，如何退出一个指定bot?

**Comment by Him188** [comment]
`Bot.close()`

**Comment by osanllyer** [comment]
console 不支持这个功能，希望将来增加吧

**Comment by Him188** [comment]
@osanllyer `Bot.getInstance()` 获得当前在线的 `Bot` 列表

**Comment by Karlatemp** [comment]
我认为这个issue说的应该是console没有退出bot的命令
