### ISSUE TITLE
创建SimpleCommand时无法指定description参数

### ISSUE THREAD

**Issue by StageGuard** [mamoe/mirai-console#231]
![QQ截图20201204165137](https://user-images.githubusercontent.com/45701251/101142748-fc1d6300-3650-11eb-8b2d-83c45e6fae86.png)
如图，`description`参数被识别为指令名称。

**Comment by Him188** [comment]
可以先 `@Suppress("ILLEGAL_COMMAND_NAME")

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/106403098-d1d8fd80-6467-11eb-9ce2-6d8d439afe04.png)
已在 2.2.0 修复
