### ISSUE TITLE
[Feature Request] 多级指令 sub-sub-command

### ISSUE THREAD

**Issue by 45gfg9** [mamoe/mirai-console#237]
在未来是否会支持多级指令的形式 例如
```
/command <arg>
/command sub <arg>
/command set opta
/command set optb <arg>
```

**Comment by Him188** [comment]
现在就支持，在 CompositeCommand 使用 `@SubCommand("set opta")`

**Comment by 45gfg9** [comment]
草（
`@SubCommand`可以带空格啊
我还在等代码方式（快进到套娃

**Comment by Him188** [comment]
SubCommand.value 会被空格分隔然后按顺序转换为 AbstractCommandValueParameter.StringContant，而且会被冲突时优先选择：
/cmd sub <string>
/cmd sub abc
若调用参数提供 abc，即使 abc 满足 <string> 类型要求，也会优先选择符合 StringConstant 的“强”（完全）匹配
