### ISSUE TITLE
Yaml读取bug

### ISSUE THREAD

**Issue by bloodyrabbit** [mamoe/mirai-console#238]
我使用mirai的存储方法把语言库的数据存储到了本地yaml，语言库出现了英语的逗号，语言库使用Map类型存。关闭存储正常但是启动的时候读取数据的时候因为逗号的存在读取报错了。数据被自动清除。
mirai－console－1.1.0

**Comment by Karlatemp** [comment]
错误代码与错误yaml与读取部分代码

**Comment by bloodyrabbit** [comment]
尝试多次复现这个bug无果，猜测可能是存储数据过多导致变成json格式。然后存储了逗号导致反序列化报错。
当时出错反手关闭了终端，未保存下日志。记忆中指向了其中一句话的逗号错误。
原错误的yaml被自动删除了

**Comment by Karlatemp** [comment]
由于没有有效信息，无法确定错误原因


close #238
