### ISSUE TITLE
插件加载顺序

### ISSUE THREAD

**Issue by liujiahua123123** [mamoe/mirai-console#24]
插件A 依赖 插件B
加载时顺序 插件B Main, 插件A Main
但是还不能确保onLoad/onEnable/onDisable 也是这个顺序

**Comment by copydog** [comment]
可以考虑用yaml或properties配置插件顺序 @Him188

**Comment by Him188** [comment]
> 可以考虑用yaml或properties配置插件顺序 @Him188

目前有`depends`配置，我们正在考虑的是 `onLoad`，`onEnable` 在复杂依赖时的调用顺序
