### ISSUE TITLE
安卓平台 kotlin无法实现MiraiConsoleImplementation

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai-console#241]
当我试图实现接口时：
class AndroidMiraiConsoleImplementation : MiraiConsoleImplementation {
然后报错：
Inheritance from an interface with '@JvmDefault' members is only allowed with -Xjvm-default option

换成1.0-M1 则不报错

版本：2.0-M1-1

**Comment by Him188** [comment]
需要添加编译器参数 `-Xjvm-default=all`

**Comment by Him188** [comment]
`build.gradle.kts`:
```kotlin
kotlin.compilations.all {
        kotlinOptions.freeCompilerArgs += "-Xjvm-default=all"
}
```

**Comment by zhaodice** [comment]
@Him188 
添加这个代码
kotlin.compilations.all {
        kotlinOptions.freeCompilerArgs += "-Xjvm-default=all"
    }
报错
A problem occurred evaluating project ':app'.
> Could not get unknown property 'compilations' for extension 'kotlin' of type org.jetbrains.kotlin.gradle.dsl.KotlinAndroidProjectExtension.
然后我改成
kotlinOptions {
        jvmTarget = "1.8"
        freeCompilerArgs = ['-Xjvm-default=all']
    }
后就正常了，问题解决
