### ISSUE TITLE
MiraiConsoleImplementation 使用了较高的安卓API

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai-console#242]
Call requires API level 26 (current min is 22): java.nio.file.Paths#get

其中MiraiConsoleImplementation使用了Path类，而Path类需要Paths.get()获取实例，Paths.get则要求安卓26 Oreo(Android O)（奥利奥）
个人认为这个版本号要求对现有的手机要求较高，android studio提示只有60.8%的手机支持安卓O的API，当然如果这是充分考虑过的可以忽略。

**Comment by zhaodice** [comment]
override val rootDir: File
        get() = getExternalFilesDir(null)!!.absoluteFile
https://github.com/mzdluo123/MiraiAndroid/blob/4cd1fccd24ef6822ab84616ef859407fcd65ef90/app/src/main/java/io/github/mzdluo123/mirai/android/service/BotService.kt
查阅到miraiAndroid用的还是File实列（371行）

**Comment by Karlatemp** [comment]
try `File("").toPath()`

**Comment by zhaodice** [comment]
@Karlatemp 
不可以

Call requires API level 26 (current min is 22): java.io.File#toPath

**Comment by zhaodice** [comment]
看见Path似乎是一个接口类，如果我手动实现的话。。。也许可能可以手动实现一个？我再看一下吧

**Comment by zhaodice** [comment]
> 
> 
> 看见Path似乎是一个接口类，如果我手动实现的话。。。也许可能可以手动实现一个？我再看一下吧

好吧我承认有点不自量力，这东西有点像套娃，不太好实现

**Comment by Him188** [comment]
Mirai 就是要求 Android 8 以上

**Comment by mzdluo123** [comment]
如果需要在Android版本低于8的设备上使用的话，建议DIY能力较强的用户尝试Termux或者是其他基于proot，chroot的Linux子系统软件运行arm版本的jre来启动console。
