### ISSUE TITLE
验证session时提示bot不存在

### ISSUE THREAD

**Issue by moheng233** [mamoe/mirai-console#243]
![image](https://user-images.githubusercontent.com/57742561/103091699-f9020b00-462f-11eb-8559-9b91e6b33a17.png)
![image](https://user-images.githubusercontent.com/57742561/103091702-fc959200-462f-11eb-84d0-27a6aa626e1e.png)
http插件版本是1.9.2
![image](https://user-images.githubusercontent.com/57742561/103091709-fef7ec00-462f-11eb-961f-dc83f34e0fa3.png)

https://github.com/project-mirai/mirai-api-http/issues/230#issue-774231687
> 我估摸着是console的问题

> 配置没有问题
因为有的时候出现登陆一下就好了，但是一会就双找不到了

**Comment by Him188** [comment]
使用 2.0-M1-1
