### ISSUE TITLE
Win系统时的那个cmd窗口，可不可以隐藏了

### ISSUE THREAD

**Issue by zhangshikj** [mamoe/mirai-console#25]
我强迫症犯了，看着这个黑乎乎的窗口，越来越不舒服按了个关闭然后界面什么的都没有了，我觉得需要个隐藏

**Comment by PeratX** [comment]
不是你觉得 我要我觉得

**Comment by PeratX** [comment]
问题描述不清，已关闭。

**Comment by masnn** [comment]
> 问题描述不清，已关闭。

是指.jar运行的窗口.... 估计是想要headless版

**Comment by zhangshikj** [comment]
指的是那个点击bat运行的窗口，我觉得在UI界面运行后，可以隐藏掉那个东西------------------ 原始邮件 ------------------
发件人: "undefined"<notifications@github.com>
发送时间: 2020年4月1日(星期三) 下午5:53
收件人: "mamoe/mirai-console"<mirai-console@noreply.github.com>;
抄送: "zhangshikj"<1372362033@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [mamoe/mirai-console] Win系统时的那个cmd窗口，可不可以隐藏了 (#25)




  
问题描述不清，已关闭。
  
是指.jar运行的窗口.... 估计是想要headless版
 
&mdash;

**Comment by masnn** [comment]
建议使用 nssm

**Comment by zhangshikj** [comment]
emmmmm------------------ 原始邮件 ------------------
发件人: "undefined"<notifications@github.com>
发送时间: 2020年4月1日(星期三) 下午5:59
收件人: "mamoe/mirai-console"<mirai-console@noreply.github.com>;
抄送: "zhangshikj"<1372362033@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [mamoe/mirai-console] Win系统时的那个cmd窗口，可不可以隐藏了 (#25)




 
建议使用 nssm
 
&mdash;
