### ISSUE TITLE
找不到net.mamoe:mirai-console-pure:2.0-M2-1-dev-1包

### ISSUE THREAD

**Issue by liuliwanzi** [mamoe/mirai-console#253]
Execution failed for task ':kaptTestKotlin'.
> Could not resolve all files for configuration ':testCompileClasspath'.
   > Could not find net.mamoe:mirai-console-pure:2.0-M2-1-dev-1.
     Searched in the following locations:
       - file:/C:/Users/����/.m2/repository/net/mamoe/mirai-console-pure/2.0-M2-1-dev-1/mirai-console-pure-2.0-M2-1-dev-1.pom
       - https://jcenter.bintray.com/net/mamoe/mirai-console-pure/2.0-M2-1-dev-1/mirai-console-pure-2.0-M2-1-dev-1.pom
       - https://repo.maven.apache.org/maven2/net/mamoe/mirai-console-pure/2.0-M2-1-dev-1/mirai-console-pure-2.0-M2-1-dev-1.pom
     Required by:
         project :

**Comment by Him188** [comment]
看文档，现在没有 pure 了

**Comment by liuliwanzi** [comment]
但是gradle还会去下载这个包

**Comment by liuliwanzi** [comment]
> 看文档，现在没有 pure 了
但是gradle还会去下载这个包
