### ISSUE TITLE
Too Long Id

### ISSUE THREAD

**Issue by bingling-sama** [mamoe/mirai-console#254]
# 太长的 QQ 账号
我尝试从内存加载 JVM 插件
但在调用 `MiraiConsole.INSTANCE.addBot()` 时
却提示我入参的 QQ id 太长
超过了 MiraiConsole 里定义的 Long 类型

> 我的 SDK 平台是 Java
> 此处附上代码截图
![image](https://user-images.githubusercontent.com/65523047/103481099-89500500-4e13-11eb-8735-d1cede872ce5.png)

**Comment by Him188** [comment]
数据类型是long，加个L

**Comment by bingling-sama** [comment]
哦好的 Thx
