### ISSUE TITLE
readme 中的title和logo图片失效了呀

### ISSUE THREAD

**Issue by 2219160052** [mamoe/mirai-console#257]
这两个图片看不到了
![image](https://user-images.githubusercontent.com/31033119/104150676-98d3dd00-5415-11eb-9a7b-9ada0f375cbe.png)

**Comment by Him188** [comment]
github 图片服务器有墙

**Comment by 2219160052** [comment]
> github 图片服务器有墙
我开代理了呀。图片的两个链接点开显示的是not found
![image](https://user-images.githubusercontent.com/31033119/104151118-19470d80-5417-11eb-8a21-a8955476b40f.png)
如果不开代理的话，用户头像和下面的社区成员头像也显示不了的
![image](https://user-images.githubusercontent.com/31033119/104151159-3d0a5380-5417-11eb-8e70-4e38a42ecc15.png)

**Comment by Him188** [comment]
确实..我也看不到了

**Comment by Him188** [comment]
fixed
