### ISSUE TITLE
能不能写个使用java的样例

### ISSUE THREAD

**Issue by GSCSDSUN** [mamoe/mirai-console#260]
kotlin实在是不会

**Comment by pf666nb** [comment]
同求

**Comment by Him188** [comment]
Java 示例会在1-2周内添加

**Comment by Eiriksgata** [comment]
如果着急着要的话，可以参考我的一个项目：https://github.com/Eiriksgata/mirai-rulateday-dice
由Java+Maven构成

**Comment by Him188** [comment]
> 如果着急着要的话，可以参考我的一个项目：https://github.com/Eiriksgata/mirai-rulateday-dice
> 由Java+Maven构成

使用中有没有遇到什么不顺的地方？最近会修改文档希望参考你的建议

**Comment by Eiriksgata** [comment]
> > 如果着急着要的话，可以参考我的一个项目：https://github.com/Eiriksgata/mirai-rulateday-dice
> > 由Java+Maven构成
> 
> 使用中有没有遇到什么不顺的地方？最近会修改文档希望参考你的建议

我感觉还好，可能就是文档一些细节没有写的很明显，需要反复查看几遍才清楚。
还有就是对于不了解整个体系结构的人来说，学起来可能比较费劲。其实最大的问题应该是文档的问题，脉络不是很清晰，没有侧重点。
