### ISSUE TITLE
Allow undersore in plugin id of JvmPluginDescription

### ISSUE THREAD

**Issue by LinHeLurking** [mamoe/mirai-console#263]
如图: 
![image](https://user-images.githubusercontent.com/35602373/104836276-d047fb00-58e7-11eb-821c-ed9f458f609b.png)
Group Id 中的下划线被提示错误, 可是按照 Java 的命名约定, 域名中带有 `-` 符号的是应该转换为 `_` 的, 所以这个检查是不是有点问题?

**Comment by Him188** [comment]
我觉得应该允许 `_`
