### ISSUE TITLE
无法正常启动Mirai Console

### ISSUE THREAD

**Issue by zixuan2020** [mamoe/mirai-console#271]
## 环境
- ubuntu18.04
- openjdk version "1.8.0_275"

## 问题
根据**Mirai Console - Run.md**步骤操作
![image](https://user-images.githubusercontent.com/20490066/105624599-fb899780-5e5d-11eb-9277-399d498641f5.png)
![image](https://user-images.githubusercontent.com/20490066/105624632-4b685e80-5e5e-11eb-9fe8-b9024c159293.png)
![image](https://user-images.githubusercontent.com/20490066/105624676-97b39e80-5e5e-11eb-917c-63423ee2c5de.png)

**Comment by Him188** [comment]
请检查版本号，mirai-console 使用 2.0.0，mirai-core 使用 2.1.0

**Comment by Him188** [comment]
或者使用自动启动器 mirai-console-loader

**Comment by Karlatemp** [comment]
请 `mkdir libs & mv *.jar libs`

**Comment by zixuan2020** [comment]
> 请 `mkdir libs & mv *.jar libs`

根据当前操作已正常,非常感谢
![image](https://user-images.githubusercontent.com/20490066/105626112-ccc4ee80-5e68-11eb-9f2e-ed86d71924d2.png)
