### ISSUE TITLE
AutoLogin.yml中多个账号被自动删除

### ISSUE THREAD

**Issue by developer-ken** [mamoe/mirai-console#274]
复现：  
·在AutoLogin.yml中设置多个账号  
·使用mcl开启miraiconsole
·关闭miraiconsole
·开启miraiconsole

AutoLogin.yml中仅剩下第一个账号。

**Comment by Him188** [comment]
可能是格式有误? yaml 缩进严格, 请检查

**Comment by developer-ken** [comment]
> 可能是格式有误? yaml 缩进严格, 请检查

第一次开启miraiconsole的时候两个账号都能够正常识别和登录，第二次就剩下一个帐号了
如果yaml格式错误，第一次应当也无法读取出账号

这个问题是在使用supervisor启动mcl时发现的，后尝试了直接敲./mcl启动，启动完成后Ctrl+C终止，问题仍然存在。

系统是Debian 4.19.0-13-amd64，运行于openjdk 11.0.9.1
`root@debian-secsever:~/mirai# uname -a
Linux debian-secsever 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
root@debian-secsever:~/mirai# java --version
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1deb10u2)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1deb10u2, mixed mode, sharing)
`

**Comment by Him188** [comment]
请提供设置好的 AutoLogin.yml 以供测试. 注意去除敏感信息

**Comment by Him188** [comment]
经测试功能正常, 重启后仍然能登录多个账号

**Comment by I-love-study** [comment]
本人近期也遇到了这个问题
