### ISSUE TITLE
使用插件 ID 作为配置文件夹名称

### ISSUE THREAD

**Issue by Nambers** [mamoe/mirai-console#276]
建议根据插件JvmPluginDescription下的id属性构建配置文件夹而不是name属性，在data文件夹下
1. 构建id可以在一定程度上避免重复导致的覆盖什么的问题
2. name一般都包含中文，而中文在一些代码里可能会兼容异常，id就不会
3. 根据定义来看，貌似用ID构建会更合理一点

**Comment by Karlatemp** [comment]
如果要支持可能会对现在的文件数据结构造成很大影响, 或许可以添加个注解使用了该注解的数据存储使用 ID, 以前的保持 name 不变

**Comment by Him188** [comment]
或许可以自动迁移，如果存在插件名称的目录就更名

**Comment by Nambers** [comment]
嗯，我觉得可以在JvmPluginDescription加个参数？或者加个修饰符来指定创建方法
另: 我觉得mirai的版本设置也可以统一下，目前的指定版本要改3个地方，JvmPluginDescription，plugin.yml，和build.gradle.kt
我觉得plugin.yml这个东西应该可以完全被JvmPluginDescription取代了吧？
@Him188

**Comment by Him188** [comment]
> 嗯，我觉得可以在JvmPluginDescription加个参数？或者加个修饰符来指定创建方法
> 另: 我觉得mirai的版本设置也可以统一下，目前的指定版本要改3个地方，JvmPluginDescription，plugin.yml，和build.gradle.kt
> 我觉得plugin.yml这个东西应该可以完全被JvmPluginDescription取代了吧？
> @Him188

提供 JvmPluginDescription 就不需要 plugin.yml 了。在未来可能会支持只修改 Gradle 项目版本而在编译时自动应用。

**Comment by Nambers** [comment]
> > 嗯，我觉得可以在JvmPluginDescription加个参数？或者加个修饰符来指定创建方法
> > 另: 我觉得mirai的版本设置也可以统一下，目前的指定版本要改3个地方，JvmPluginDescription，plugin.yml，和build.gradle.kt
> > 我觉得plugin.yml这个东西应该可以完全被JvmPluginDescription取代了吧？
> > @Him188
> 
> 提供 JvmPluginDescription 就不需要 plugin.yml 了。在未来可能会支持只修改 Gradle 项目版本而在编译时自动应用。

嗯，也就是说目前已经可以把plugin.yml从项目删除了吧？ok
