### ISSUE TITLE
启动mirai-console-loader NoSuchProviderException

### ISSUE THREAD

**Issue by zixuan2020** [mamoe/mirai-console#280]
# 环境
- MacOs 10.15.6
- JDK "11.0.7" 2020-04-14 LTS
- mirai-console-2.3.0.jar mirai-console-terminal-2.3.0 mirai-core-all-2.3.0

# 问题
**./mcl 启动时抛出**
![image](https://user-images.githubusercontent.com/20490066/106709054-e287a000-662e-11eb-8cbf-b1b4ebadade5.png)
![image](https://user-images.githubusercontent.com/20490066/106709302-3f835600-662f-11eb-9f44-addcf242c1d0.png)

**Comment by Him188** [comment]
看 core 的文档, 不支持 oracle JDK, 要用任意其他 JDK

**Comment by PeratX** [comment]
mcl已添加oraclejdk.js，请手动下载该js并放到scripts目录下尝试

**Comment by zixuan2020** [comment]
> mcl已添加oraclejdk.js，请手动下载该js并放到scripts目录下尝试

手动添加后已正常,感谢
