### ISSUE TITLE
插件读取yml配置文件有误

### ISSUE THREAD

**Issue by 2314933036** [mamoe/mirai-console#306]
![image](https://user-images.githubusercontent.com/38069007/110404422-c8236500-80b9-11eb-824b-aa1d7dac98a6.png)

未启动mcl情况下修改完插件配置再启动mcl
插件报连接数据库错误
插件配置文件变为
![image](https://user-images.githubusercontent.com/38069007/110404584-120c4b00-80ba-11eb-8a9b-d57175fa014a.png)

**Comment by Him188** [comment]
请问这是什么插件

**Comment by 2314933036** [comment]
> 请问这是什么插件

https://github.com/KonnyakuCamp/SuperCourseTimetableBot/issues/7

**Comment by Him188** [comment]
这个问题要找到原因非常复杂, 不仅涉及 yamlkt 还与 PluginData 有关, 将会首先保证 yamlkt 稳定再来处理这个问题.
