### ISSUE TITLE
JAutoSavePluginData读取失败

### ISSUE THREAD

**Issue by Len-Jon** [mamoe/mirai-console#311]
```java
public class MyJavaData extends JAutoSavePluginData {
    public static final MyJavaData INSTANCE = new MyJavaData("data");

    public final Value<Set<String>> BLANK_LIST = typedValue(createKType(Set.class, createKType(String.class)));

    public MyJavaData(@NotNull String saveName) {
        super(saveName);
    }
}
```

```java
public class Main extends JavaPlugin {
    public static Main INSTANCE = new Main();

    private Main() {
        super(/*...*/);
    }

    @Override
    public void onLoad(@NotNull PluginComponentStorage onLoad) {
        this.reloadPluginData(MyJavaData.INSTANCE);
    }
}
```

在mcl1.0.5中启动时报错：

> 2021-03-14 14:29:22 E/main: Failed to init MiraiConsole.
> net.mamoe.mirai.console.plugin.loader.PluginLoadException: Exception while loading search-helper
>         at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:110)
>         at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
>         at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:36)
>         at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:85)
>         at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:141)
>         at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:152)
>         at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
>         at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
>         at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
>         at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>         at org.itxtech.mcl.Utility.bootMirai(Utility.java:76)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>         at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
>         at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
>         at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
>         at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
>         at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
>         at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
>         at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
>         at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
>         at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
>         at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
>         at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
>         at org.mozilla.javascript.Context.call(Context.java:554)
>         at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
>         at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
>         at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
>         at com.sun.proxy.$Proxy4.run(Unknown Source)
>         at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
>         at org.itxtech.mcl.Loader.start(Loader.java:129)
>         at org.itxtech.mcl.Loader.main(Loader.java:53)
> Caused by: java.lang.ExceptionInInitializerError
>         at top.lenjon.plugin.Main.onLoad(Main.java:37)
>         at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnLoad$mirai_console(JvmPluginInternal.kt:196)
>         at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:108)
>         ... 37 more
> Caused by: java.lang.IllegalArgumentException: Star projection must have no type specified.
>         at kotlin.reflect.KTypeProjection.<init>(KTypeProjection.kt:35)
>         at net.mamoe.mirai.console.data.java.JAutoSavePluginData$Companion.createKType(JAutoSavePluginData.kt:154)
>         at net.mamoe.mirai.console.data.java.JAutoSavePluginData$Companion.createKType(JAutoSavePluginData.kt:164)
>         at net.mamoe.mirai.console.data.java.JAutoSavePluginData.createKType(JAutoSavePluginData.kt)
>         at top.lenjon.plugin.MyJavaData.<init>(MyJavaData.java:16)
>         at top.lenjon.plugin.MyJavaData.<clinit>(MyJavaData.java:14)
>         ... 40 more

**Comment by Him188** [comment]
```
Caused by: java.lang.IllegalArgumentException: Star projection must have no type specified.
at kotlin.reflect.KTypeProjection.(KTypeProjection.kt:35)
at net.mamoe.mirai.console.data.java.JAutoSavePluginData$Companion.createKType(JAutoSavePluginData.kt:154)
at net.mamoe.mirai.console.data.java.JAutoSavePluginData$Companion.createKType(JAutoSavePluginData.kt:164)
at net.mamoe.mirai.console.data.java.JAutoSavePluginData.createKType(JAutoSavePluginData.kt)
at top.lenjon.plugin.MyJavaData.(MyJavaData.java:16)
at top.lenjon.plugin.MyJavaData.(MyJavaData.java:14)
... 40 more
```

**Comment by Len-Jon** [comment]
对不起，还是没有明白什么意思，机翻给出的释义是

> 星形投影不得指定任何类型。

和类型有关的地方

我是用的是[这里](https://github.com/mamoe/mirai-console/blob/master/backend/mirai-console/src/data/java/JAutoSavePluginData.kt#L69)的示例，第47行中

```java
public final Value<List<String>> list = typedValue(createKType(List.class, createKType(String.class))); 
```

我原样复制粘贴也是相同的错误。

**Comment by Him188** [comment]
> 对不起，还是没有明白什么意思，机翻给出的释义是
> 
> > 星形投影不得指定任何类型。
> 
> 和类型有关的地方
> 
> 我是用的是[这里](https://github.com/mamoe/mirai-console/blob/master/backend/mirai-console/src/data/java/JAutoSavePluginData.kt#L69)的示例，第47行中
> 
> ```java
> public final Value<List<String>> list = typedValue(createKType(List.class, createKType(String.class))); 
> ```
> 
> 我原样复制粘贴也是相同的错误。

可能是 mirai 的问题，我发的这个是用来定位错误的
