### ISSUE TITLE
没找到mirai-console-terminal相关项目

### ISSUE THREAD

**Issue by Eiriksgata** [mamoe/mirai-console#315]
最近才看到Github自动编译报错，然后看了一下，原来Mirai依赖转为了中央仓库。
在中央仓库里面找到了mirai-console | mirai-core-jvm 
但是没找到mirai-console-terminal ，看了一下文档，发现唯独mirai-console-terminal是没有项目跳转的。

**Comment by Him188** [comment]
是有的吧 https://repo.maven.apache.org/maven2/net/mamoe/mirai-console-terminal/

**Comment by Him188** [comment]
转仓库是因为 JCenter 要关闭了（最近延迟到明年春季），JCenter 目前也还在同步发布构建，但不确定以后会一直有用。

**Comment by Eiriksgata** [comment]
找到了，谢谢
