### ISSUE TITLE
自动编译错误：仓库依赖缺失 

### ISSUE THREAD

**Issue by Eiriksgata** [mamoe/mirai-console#316]
2.4.0 - 2.4.2 mirai-coro-all & mirai-console 中央仓库依赖文件缺失：
1. net.mamoe:kotlin-jvm-blocking-bridge-jvm:1.10.0-dev-1
2. net.mamoe.yamlkt:yamlkt-jvm:0.7.5
3. io.github.karlatemp:caller:1.0.1

2.5-RC mirai-coro-all
1. net.mamoe.yamlkt:yamlkt-jvm:0.7.5

查阅后发现，2.4.x 用的是 `net.mamoe:kotlin-jvm-blocking-bridge-jvm:1.10.0-dev-1` ，2.5-RC 用的是`net.mamoe:kotlin-jvm-blocking-bridge-jvm:1.10.3`，中央仓库确实没有`1.10.0-dev-1` 所以报错了。
其次便是依旧缺少 `net.mamoe.yamlkt:yamlkt-jvm:0.7.5` ，去yamilkt项目看了下，看到确实有说正在往中央仓库里添加，这里催更一下，虽然目前本地使用起来因为以前存在依赖文件所以没问题，但是每次提交都AutoBuild Error 确实难受。同时对于新开发人员而言，确实缺少相关的依赖。

对于JCenter的关闭，依赖仓库调整确实很麻烦

**Comment by Him188** [comment]
可以先使用 JCenter, JCenter 会在明年才关闭

**Comment by Eiriksgata** [comment]
> 可以先带上 JCenter, JCenter 会在明年才关闭

现在访问JCenter已经是403了 不知道什么情况，我也是看到Github有Code scanning alerts 项，然后一看 Depending upon JCenter/Bintray as an artifact repository ，访问里面的资源也都是403

**Comment by Eiriksgata** [comment]
> 可以先带上 JCenter, JCenter 会在明年才关闭

行，我换回JCenter了，我主要是因为看到有Github的Security项警报，就想直接换成中央仓库了
