### ISSUE TITLE
IDEA警告Task 'wrapper' not found in project ':mirai-console-terminal'.

### ISSUE THREAD

**Issue by Aniviar** [mamoe/mirai-console#33]
当我尝试编译最新版的mirai-console-terminal时IDEA向我警告Task 'wrapper' not found in project ### ':mirai-console-terminal'.，原谅我对kotlin和Gradle不太了解，请问这个怎么解决（开发者可以发一个打包好的版本吗）自己下kotlin编译器下载了一个G的依赖后告诉我报错，心态都崩了啊T T

**Comment by Him188** [comment]
可忽略这个警告

**Comment by liujiahua123123** [comment]
mirai-console-terminal现在不在维护, 会在1.0.0发布前在维护 请使用pure

**Comment by Aniviar** [comment]
> mirai-console-terminal现在不在维护, 会在1.0.0发布前在维护 请使用pure

好吧，感谢大佬回复

**Comment by Aniviar** [comment]
> 可忽略这个警告

我尝试一下，谢谢大佬
