### ISSUE TITLE
mirai-console IDEA插件对 CompositeCommand description 的误判

### ISSUE THREAD

**Issue by iceBear67** [mamoe/mirai-console#340]
![image](https://user-images.githubusercontent.com/48877375/115335773-66ace680-a18d-11eb-8573-27096680e489.png)

**Comment by Him188** [comment]
版本是 2.6.1 吗

**Comment by iceBear67** [comment]
是的

**Comment by Him188** [comment]
可以先 `@Suppress("ILLEGAL_COMMAND_NAME")` 抑制这个错误

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/115534687-9ca3b500-a2ca-11eb-9548-a5033c5ca8e5.png)

@iceBear67 看起来功能是正常的? 请检查插件版本 
![image](https://user-images.githubusercontent.com/12100985/115534759-ae855800-a2ca-11eb-8afe-c3e140c04a78.png)

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/115537423-63207900-a2cd-11eb-8923-808088bf84a3.png)

复现了, 在位置上这个参数是 secondaryNames 才行
