### ISSUE TITLE
AbstractPermitteeId类无法访问

### ISSUE THREAD

**Issue by hisou** [mamoe/mirai-console#345]
![image](https://user-images.githubusercontent.com/13644483/117100189-b7375d00-ada5-11eb-8f4c-02146ba18756.png)
版本2.6.1、2.6.3均报错

代码
`PermissionService.Companion.permit(AbstractPermitteeId.AnyContact.INSTANCE,
                PermissionId.parseFromString("*:*"));`

**Comment by Karlatemp** [comment]
带 kotlin-stdlib 了吗

**Comment by hisou** [comment]
`dependencies {

    compileOnly 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'

    compile("org.jsoup:jsoup:1.13.1")
    api("net.mamoe:mirai-core:$miraiCoreVersion")
    api("net.mamoe:mirai-console-terminal:$miraiConsoleVersion")
    compileOnly "net.mamoe:mirai-console:$miraiConsoleVersion"

    testImplementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
    testImplementation "net.mamoe:mirai-core:$miraiCoreVersion"
    //testImplementation "net.mamoe:mirai-core-qqandroid:1.1.3"
    testImplementation "net.mamoe:mirai-console:$miraiConsoleVersion"

}`

**Comment by Him188** [comment]
mirai 版本太旧, 阅读文档

**Comment by hisou** [comment]
开头说了mirai和console均已经更新到2.6.3

**Comment by hisou** [comment]
问题仍然存在，只要import了AbstractPermitteeId类直接可以复现

**Comment by Him188** [comment]
是不是文件损坏了？试试用 2.6.4

**Comment by Samarium150** [comment]
从IDEA新建mirai-console项目语言选Java然后在Plugin.java里加一行
`import net.mamoe.mirai.console.permission.AbstractPermitteeId;`
好像就能复现了

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/124345506-d74f9500-dc0b-11eb-87e7-6df813d0fe5d.png)

应该是 IDE 的问题

2.7-M1 + Kotlin 1.5.20 + IU-211.7442.40, IDE 正常. 编译正常.
