### ISSUE TITLE
可不可以提供一个比较好的方式去debug

### ISSUE THREAD

**Issue by 250king** [mamoe/mirai-console#361]
我写了一个Mirai Console的插件，但总是出问题，结果因为不支持实时debug（断点、变量查看）导致花了很长时间才弄完，而且只能用一些很简陋的方式（log输出变量）去debug，效率比较低。就可不可以提供一个比较好的途径更方便地去debug。

**Comment by Him188** [comment]
是支持的，启动一个 terminal 前端即可

**Comment by Karlatemp** [comment]
在论坛中有相关的讨论和解答 https://mirai.mamoe.net/topic/246/

**Comment by 250king** [comment]
但生成的项目没有test……
![image](https://user-images.githubusercontent.com/61256966/120986290-04488d80-c7af-11eb-98b5-25a8fc69f657.png)

**Comment by Him188** [comment]
> 但生成的项目没有test……
> ![image](https://user-images.githubusercontent.com/61256966/120986290-04488d80-c7af-11eb-98b5-25a8fc69f657.png)

...似乎确实忘了写出 RunTerminal
