### ISSUE TITLE
[建议]建议在readme中徽章处旁边加上JDK版本或者JAVA版本

### ISSUE THREAD

**Issue by 2926295173** [mamoe/mirai-console#365]

**Comment by Him188** [comment]
徽章是指什么

**Comment by 2926295173** [comment]
> 徽章是指什么

就是在 chat on bitter. 那个图标旁边加个jdk版本的小组件，个人感觉看着比较直接，比较明显

**Comment by Him188** [comment]
我认为 JDK 版本并不重要。mirai 使用目前大多数项目都至少需要的 1.8，因此没有必要过多提示使用者。在开发和运行的文档中都有关于 JDK 版本的说明。
