### ISSUE TITLE
CompositeCommand中如何传入GroupMessageEvent来发送群消息

### ISSUE THREAD

**Issue by Nekoer** [mamoe/mirai-console#392]
kotlin中在使用`CompositeCommand`时调用其它方法如何传入`GroupMessageEvent`来发送群消息
`@SubCommand("start","启动") fun CommandSender.start() {
方法(event)
}`

看了[https://github.com/mamoe/mirai-console/discussions/292](https://github.com/mamoe/mirai-console/discussions/292)发现和我需要的不太一样，请问如何使用

**Comment by Him188** [comment]
```kotlin
/**
 * 代表一个真实的 [群员][Member] 主动在群内发送消息执行指令.
 * @see MemberCommandSender 代表一个 [群员][Member] 执行指令, 但不一定是通过群内发消息方式
 */
public class MemberCommandSenderOnMessage internal constructor(
    public override val fromEvent: GroupMessageEvent,
) : MemberCommandSender(fromEvent.sender), CommandSenderOnMessage<GroupMessageEvent>
```
判断 `this` 为 `MemberCommandSenderOnMesssage` 并获取其 `fromEvent`, 可以得到 `GroupMessageEvent`

```kotlin
(this as? MemberCommandSenderOnMessage)?.fromEvent
```

**Comment by Karlatemp** [comment]
请重新描述您的问题，您的问题描述过于混乱
