### ISSUE TITLE
支持指定 data plugins 等文件夹的位置

### ISSUE THREAD

**Issue by Wybxc** [mamoe/mirai-console#394]
mirai-console 会在当前目录寻找 data plugins 等文件夹，如果想要在另一个文件夹中启动 mirai-console，就会找不到这些文件夹。

比如 mirai-console 安装在 `~/mirai`，这个文件夹的目录结构是这样的：

```
mirai
+---bots
+---config 
+---data
+---libs
|       mirai-console-2.7-M2.jar
|       mirai-console-terminal-2.7-M2.jar
|       mirai-core-all-2.7-M2.jar
|
+---plugins
|       mirai-api-http-v2.1.0.mirai.jar
|   start-mirai-console.cmd
```

而我在 `~/test` 目录输入 `~/mirai/start-mirai-console.cmd` 命令，不会加载 `~/mirai/plugins` 中的插件。mirai-console 会在 `~/test` 中创建新的 `bots` `config` `data` `plugins` 目录。

应该增加一个启动参数，允许指定这些文件的位置。类似这样：

```
~/mirai/start-mirai-console.cmd --dir=~/mirai
```

**Comment by Karlatemp** [comment]
1. console-terminal 支持使用 `-Duser.dir=...` 指定 console 运行目录
2. console 运行目录由前端指定, terminal 已经具有此功能
3. 无法保证所有插件都使用 console 提供的数据目录 api, 可能会有插件会直接使用 `new File`, 忽略 console 的设置 (important)
4. shell 脚本加上一行 `cd` 语句并不困难

**Comment by Wybxc** [comment]
感谢
