### ISSUE TITLE
把jar放到plugins文件夹mirai没有读取jar

### ISSUE THREAD

**Issue by andogy** [mamoe/mirai-console#406]
## 问题

我把我自己的jar放到plugins里面，mirai没有读取jar

### 版本
```
mirai-console: 2.7.0
mirai-core: 2.7.0
```

### 截图
![image](https://user-images.githubusercontent.com/76235521/131423501-07bc4b19-86ca-4a2e-8a0f-bea9c5d7166c.png)
![image](https://user-images.githubusercontent.com/76235521/131423619-5665616b-e99a-45fa-aa86-a0a01ee77e09.png)

> 我试过使用mcl指令来添加，但是报错了，无法读取

**Comment by andogy** [comment]
> 是否有 META-INF/services/net.mamoe.mirai.console.plugin.Plugin ?

没有，如何解决？

**Comment by Him188** [comment]
https://github.com/mamoe/mirai-console/blob/master/docs/Plugins.md#%E9%85%8D%E7%BD%AE%E4%B8%BB%E7%B1%BB%E6%9C%8D%E5%8A%A1

**Comment by andogy** [comment]
> https://github.com/mamoe/mirai-console/blob/master/docs/Plugins.md#%E9%85%8D%E7%BD%AE%E4%B8%BB%E7%B1%BB%E6%9C%8D%E5%8A%A1

我使用了java，看起来那种方式并不适合我，没有显示mirai图标也没有叫我配置
![image](https://user-images.githubusercontent.com/76235521/131432539-ef8a8097-80b9-447f-9f00-d9fbf1da6417.png)

**Comment by Him188** [comment]
https://github.com/mamoe/mirai-console/blob/master/docs/Plugins.md#%E6%89%8B%E5%8A%A8%E9%85%8D%E7%BD%AE%E4%B8%BB%E7%B1%BB%E6%9C%8D%E5%8A%A1

**Comment by Him188** [comment]
建议使用 IDE 插件自动创建项目, 确保 IDE 是 2020.1 及以上版本

**Comment by andogy** [comment]
> 建议使用 IDE 插件自动创建项目, 确保 IDE 是 2020.1 及以上版本

是插件构建的，并且ide为2020.1.*

**Comment by andogy** [comment]
不，还是不行

**Comment by Karlatemp** [comment]
根据 `import net.mamoe.mirai.console.plugins.PluginBase` 判断你的项目结构包括依赖都是 1.x 时的格式, 请更新
