### ISSUE TITLE
权限设置问题

### ISSUE THREAD

**Issue by EnderAvaritia** [mamoe/mirai-console#409]
perm permit * * 之后再执行perm deny * 删了几个权限，机器人回复ok了，但是perm pp查自己还是显示*：*，权限不能删除

```

```

#### 版本及相关选项选择

- mirai-core: `2.7.1` 
- bot-protocol: ` ANDROID_PAD` 

#### 网络日志

```

```

**Comment by Karlatemp** [comment]
在 Console 内置系统中, 你已经把 `*:*` 给予了 `A`

`perm deny` 的操作是从一给予的权限中取消某条具体权限的给予, 但是 `A` 因为拥有 `*:*` 所以 `A` 是系统最高管理员, 依然拥有全部权限

如果需要更详细的权限管理, 请安装第三方权限插件

**Comment by EnderAvaritia** [comment]
> 在 Console 内置系统中, 你已经把 `*:*` 给予了 `A`
> 
> `perm deny` 的操作是从一给予的权限中取消某条具体权限的给予, 但是 `A` 因为拥有 `*:*` 所以 `A` 是系统最高管理员, 依然拥有全部权限
> 
> 如果需要更详细的权限管理, 请安装第三方权限插件

就是说即使是在控制台操作，也不能将最高管理员的某项特定权限移除？
那是否存在某种方式，在给予权限的同时不给予最高管理员？（毕竟权限一个一个打太要命了）

**Comment by Karlatemp** [comment]
一个一个给权限 / 给插件的 root 权限 / 使用第三方权限插件

**Comment by EnderAvaritia** [comment]
> 一个一个给权限 / 给插件的 root 权限 / 使用第三方权限插件

好吧，那问一下，之后会有单独删除权限的功能的计划吗？

**Comment by Him188** [comment]
> > 一个一个给权限 / 给插件的 root 权限 / 使用第三方权限插件
> 
> 好吧，那问一下，之后会有单独删除权限的功能的计划吗？

没有，内置权限系统不容易支持这些
