### ISSUE TITLE
改善Pure CLI交互体验

### ISSUE THREAD

**Issue by 45gfg9** [mamoe/mirai-console#41]
OS: macOS 10.15.4
mirai-core: 0.34.0
mirai-console-wrapper: 0.2.0
mirai-console-pure: 0.4.6

---

* 当前CLI的`stdin`和`stdout`是混在一起的，导致正在输入指令时若接收消息就会将前部分输入带上去

* 在后台使用`/say`发送消息时消息不支持空格 用单/双引号括住也不行

* 无法用<kbd>↑</kbd><kbd>↓</kbd>键跳转输入历史（按键会转成类似`^[[A`字符序列，Linux未测试，不知道是不是macOS / iTerm2特性）

* 无法用<kbd>←</kbd><kbd>→</kbd>修正当前指令（同上）

* 中文字符需要两次<kbd>Backspace</kbd>删除

* 空输入（只按<kbd>return</kbd>）会解析未知指令

* 当想完全放弃当前输入时很容易习惯性按`^C`，然而会直接终止mirai-console

**Comment by 45gfg9** [comment]
针对最后一点，是否可以加入类似`/stop`的功能用于关停bot及console，将`^C`用于放弃当前输入
（退一步也可以借鉴SQL，用\c放弃之前的输入）

**Comment by Him188** [comment]
确实，现在控制台需要改进

**Comment by liujiahua123123** [comment]
那是terminal版 会在1.0.0发布

**Comment by liujiahua123123** [comment]
pure是保证所有版本都能用的
因此才会有terminal/graphical版
