### ISSUE TITLE
/help能不能用转发消息的方式

### ISSUE THREAD

**Issue by hinyb** [mamoe/mirai-console#416]
大佬，/help能不能用转发消息的方式
直接输出刷屏，影响体验o(≧口≦)o

**Comment by Him188** [comment]
可以考虑加个配置, 或者你可以自己写一个插件, 以 `/help` 注册指令, 就可以覆盖 console 内置的指令.

**Comment by Him188** [comment]
net.mamoe.mirai.console.command.BuiltInCommands.HelpCommand#generateDefaultHelp

你可以调用这个来生成默认的帮助消息
![image](https://user-images.githubusercontent.com/12100985/141009924-df32c9af-8409-44c0-bac9-aa6c78fbfea8.png)

**Comment by hinyb** [comment]
感谢大佬

**Comment by wuxianggujun** [comment]
> net.mamoe.mirai.console.command.BuiltInCommands.HelpCommand#generateDefaultHelp
> 
> 你可以调用这个来生成默认的帮助消息 ![image](https://user-images.githubusercontent.com/12100985/141009924-df32c9af-8409-44c0-bac9-aa6c78fbfea8.png)

大佬，我自己写了一个help但是并没有覆盖这个help指令
