### ISSUE TITLE
希望可以开放命令可见性，让我们可以自定义命令参数解析器

### ISSUE THREAD

**Issue by novacoo** [mamoe/mirai-console#425]
希望InternalCommandValueArgumentParserExtensions接口可以修改为public供我们自定义CommandValueArgumentParser

**Comment by novacoo** [comment]
额抱歉看错地方了

**Comment by Him188** [comment]
Command 有个 context 参数, 更新那个 context 就可以了

**Comment by novacoo** [comment]
这比我想到的还要简单一些啊，感谢Herobrine
