### ISSUE TITLE
Update installed (plugins from PluginCenter) before load plugin(s)

### ISSUE THREAD

**Issue by saeziae** [mamoe/mirai-console#49]
As the title.

**Comment by saeziae** [comment]
As an old plugin is possibly not compatible to a new version of console.

**Comment by Chenwe-i-lin** [comment]
I think this is unreasonable. plugins donot need to be automatically updated with mirai-core and mirai-console, but it can be, so I think this should be controlled by the user.

**Comment by Him188** [comment]
Planned.

**Comment by liujiahua123123** [comment]
in 1.0.0

**Comment by liujiahua123123** [comment]
not offical, should be plugin(s) from PluginCenter
