### ISSUE TITLE
`/login` via sending command from plugin not available

### ISSUE THREAD

**Issue by saeziae** [mamoe/mirai-console#50]

**Comment by Him188** [comment]
Currently as designed.

**Comment by saeziae** [comment]
But it make sense that login automatically through http-api

**Comment by liujiahua123123** [comment]
plugins should NOT log in new bots

**Comment by BeautyYuYanli** [comment]
If you use [miraiOK](https://github.com/LXY1226/MiraiOK), you can edit `miraiOK/config.txt` to do this
