### ISSUE TITLE
Graphical无法正确处理带有设备锁的账号登录

### ISSUE THREAD

**Issue by mzdluo123** [mamoe/mirai-console#57]
现象为反复要求输入验证码
![image](https://user-images.githubusercontent.com/23146087/79571703-394ada00-80ee-11ea-85a0-28e6cf13578f.png)

**Comment by Him188** [comment]
并需要在登录失败时打印堆栈信息, 而不是只打印 message

**Comment by Him188** [comment]
由于 mirai-console-graphical 已经不再更新, 关闭 issue.
