### ISSUE TITLE
让 Command 自动解析参数类型

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai-console#64]
可通过反射等方法自动解析参数为 `Int`, `Long` 等类型。

在指令注册时注册子指令，例如：
注册子指令 `/forward add <groupId>`，则子指令的 `onCommand` 只接受一个参数 `groupId: Long`，配合上述自动类型解析

**Comment by Chenwe-i-lin** [comment]
难道不能通过生成正则匹配字符串的方式来解决问题吗

**Comment by Him188** [comment]
最好是强参数匹配，而不是字符串 Map

**Comment by Chenwe-i-lin** [comment]
可以将生成的字符串通过各个参数附加的 `flags`(可以通过反射获取函数的参数定义吧), 直接转换为其对应的值

**Comment by Chenwe-i-lin** [comment]
顺带一提, python-mirai 就是使用这种方式进行指令的解析的
