### ISSUE TITLE
/install 显示不全

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai-console#68]
![image](https://user-images.githubusercontent.com/12100985/80101329-d2bd3480-85a3-11ea-9943-8967c2c1344d.png)
![image](https://user-images.githubusercontent.com/12100985/80101355-db156f80-85a3-11ea-9ae8-6aa0948fa5ec.png)

可见 `mirai-api-http` 等插件均未显示

**Comment by liujiahua123123** [comment]
转移问题到CuiCloud或MiraiPublicAPI项目
