### ISSUE TITLE
让 Pure 版本 console 支持彩色 log

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai-console#7]

**Comment by PeratX** [comment]
Via `jansi`

**Comment by LinHeLurking** [comment]
java可以通过\u001b来插入vt100控制符, 比如这样的一个例子
```kotlin
// console log test
val red = "\u001b[38;5;196m"
val blue = "\u001b[38;5;33m"
val green = "\u001b[38;5;46m"
val yellow = "\u001b[38;5;226m"
val reset = "\u001b[39;49m"
logger.info("${red}゛ィ尔${blue}媽媽${green}言兑${yellow}我${red}老±${reset}dà﹏")
```
![image](https://user-images.githubusercontent.com/35602373/76738880-62521500-67a6-11ea-9820-a7be876222e0.png)

重载一下logger应该就可以了? ~~(实在不方便的话, 直接把常见的几个颜色码写进去让用户自己定义输出也不是不可以)~~

**Comment by LinHeLurking** [comment]
话说有人review一下这个pull request吗?
https://github.com/mamoe/mirai-console/pull/13

**Comment by liujiahua123123** [comment]
solved
