### ISSUE TITLE
插件在高版本jre下使用gson报错:java.lang.NoClassDefFoundError: java/sql/Time

### ISSUE THREAD

**Issue by CHH2000day** [mamoe/mirai-console#75]
源码如图:
![image](https://user-images.githubusercontent.com/14977308/80357794-110d6900-88ae-11ea-9558-7c1d0e8bd492.png)

错误:
![image](https://user-images.githubusercontent.com/14977308/80357232-3d74b580-88ad-11ea-8235-69bf5b32d42c.png)

插件jar里的测试代码直接运行无问题

![image](https://user-images.githubusercontent.com/14977308/80357578-c4c22900-88ad-11ea-897c-9ac2f54cb77c.png)
![image](https://user-images.githubusercontent.com/14977308/80357667-e4595180-88ad-11ea-9bcb-cb07b16f3411.png)

拿jre11试了会报错,在jre8下无问题

**Comment by Him188** [comment]
这并不是 mirai 或 mirai-console 问题

**Comment by Him188** [comment]
Json 序列化请使用 [`kotlinx.serializaion`](https://github.com/kotlin/kotlinx.serialization), mirai bundle这个库
