### ISSUE TITLE
Throwable? 被以 Any? 记录在日志而导致无法看到 stacktrace

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai-console#8]
![image](https://user-images.githubusercontent.com/12100985/76377123-042bc900-6385-11ea-9b3f-4a3915860a53.png)

这两个 invoke 都 resolve 到了

![image](https://user-images.githubusercontent.com/12100985/76377130-09891380-6385-11ea-8420-e2f889c222e6.png)

**Comment by liujiahua123123** [comment]
resolved
