### ISSUE TITLE
0.5.1指令提示没更新

### ISSUE THREAD

**Issue by AsakuraFuuko** [mamoe/mirai-console#80]
>  18:17:19 [INFO] [Mirai 0.5.1 Pkmon] Mirai-console 启动完成
>  18:17:19 [INFO] [Mirai 0.5.1 Pkmon] "/login qqnumber qqpassword " to login a bot
>  18:17:19 [INFO] [Mirai 0.5.1 Pkmon] "/login qq号 qq密码 " 来登录一个BOT
> /login xxxxx xxxxx
>  18:17:43 [INFO] [Command] 未知指令 /login xxxxx xxxxx

> auto-login xxxx xxxx
>  18:43:50 [ERROR] [ConsoleAddition] 请输入正确格式的QQ号和密码
>  18:43:50 [INFO] [Command] 自动保存本次登录的qq号和密码md5值，下次启动时自动登录
> /auto-login qq password

**Comment by AsakuraFuuko** [comment]
换了1.1.0的wrapper第二个问题没有了，登录指令还是不能加 /

**Comment by Karlatemp** [comment]
控制台命令本来就不应该加 / 的吧

**Comment by AsakuraFuuko** [comment]
之前的版本好像要加 / ？忘了

**Comment by Him188** [comment]
问题是什么？

**Comment by AsakuraFuuko** [comment]
> 问题是什么？

指令的提示没更新，不知道是不是因为改了这个设定，console addition那个插件没有用了

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/81174272-22ecbb80-8fd4-11ea-9671-371ef044cd2e.png)
控制台指令w无需加 '/'

**Comment by Him188** [comment]
这应该成为常识, 因为(部分)指令的 usage 是插件控制因而无法针对控制台提示.

并且没有必要为控制台专门设立提示
