### ISSUE TITLE
Windows版本无限跳验证码问题

### ISSUE THREAD

**Issue by tobycroft** [mamoe/mirai-console#88]
![QQ截图20200520224755](https://user-images.githubusercontent.com/24893075/82460961-712dae80-9aec-11ea-810f-d6a3f5933a83.jpg)

大概就是这样的了

输入正确依然会继续跳验证码，这是github下载的3.3版本

**Comment by liujiahua123123** [comment]
我更关心那个未知指令/login

**Comment by Him188** [comment]
> 我更关心那个未知指令/login

之前在某个PR里被改掉了，删了自动去除/
后来一直懒得更新

**Comment by wqy0916** [comment]
请问你这个在哪里下载的

**Comment by Him188** [comment]
由于 mirai-console-graphical 已经不再更新, 关闭 issue.
